app:
  filter:
    noInterceptUrl: /login,swagger-ui.html

#自定义服务路由
zuul:
  routes:
#    prefix: /api   # 访问网关路径的前缀（在映射路径的前面，一般用于区别开发的版本）
    # 随意写的区分不同映射服务器的名称（只是区分不同的映射服务器）
    resources-interface:
     #自定义映射服务器路径的名称（相当于key，外部访问这个地址会映射到下面的service-id这个value值。
     #然后从eureka服务列表找到对应服务名称，进而负载均衡的请求一个服务器）
      path: /resources-interface/**
      # 这是写的固定映射url，可代替service-id。但是不能实现服务器的负载均衡和高可用，因为总是访问同一服务器
#      url: http://localhost:4010/
      #eureka注册中心中要映射的服务名称，因为是双层map结构，所以可以实现负载均衡和高可用
      service-id: resources-interface
      semaphore:
          max-semaphores: 1000 #针对单个服务的路由设置最大信号量
#      strip-prefix: false
#  ignoredPatterns: '*'  #忽略所有服务
  #处理http请求头为空的问题
#  sensitive-headers:
